# Labels are applied based on which files are changed in a PR.
# https://github.com/actions/labeler

automation:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

ai:
  - changed-files:
      - any-glob-to-any-file:
          - '**/ai/**'
          - '**/*prompt*'
          - '**/*llm*'

edi:
  - changed-files:
      - any-glob-to-any-file:
          - '**/edi/**'
          - '**/*edifact*'
          - '**/*x12*'

api:
  - changed-files:
      - any-glob-to-any-file:
          - '**/api/**'
          - '**/*.openapi.yml'
          - '**/*.openapi.yaml'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
          - 'requirements.txt'
          - 'poetry.lock'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - '.env.example'
          - '.editorconfig'
